-- Create table TheKnowledgeBank.Categories
CREATE TABLE IF NOT EXISTS Categories (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR(50) NOT NULL UNIQUE,
    Description VARCHAR(255) NOT NULL DEFAULT '',
    PublishedOn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedOn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
-- Create table TheKnowledgeBank.Tags
CREATE TABLE IF NOT EXISTS Tags (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR(50) NOT NULL UNIQUE,
    Description VARCHAR(255) NOT NULL DEFAULT '',
    PublishedOn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedOn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
-- INSERT DATA EXAMPLE
INSERT INTO Categories (Name, Description)
VALUES ('Programming', 'Programming'),
    ('Design', 'Design'),
    ('Business', 'Business'),
    ('Marketing', 'Marketing'),
    ('Music', 'Music'),
    ('Photography', 'Photography'),
    ('Health', 'Health'),
    ('Fitness', 'Fitness'),
    ('Education', 'Education'),
    ('Food', 'Food'),
    ('Travel', 'Travel'),
    ('Lifestyle', 'Lifestyle'),
    ('Sports', 'Sports'),
    ('Finance', 'Finance'),
    ('Entertainment', 'Entertainment'),
    ('Technology', 'Technology'),
    ('Science', 'Science'),
    ('Gaming', 'Gaming'),
    ('News', 'News'),
    ('Politics', 'Politics'),
    ('Culture', 'Culture'),
    ('Other', 'Other');
ON CONFLICT (Name) DO NOTHING;
INSERT INTO Tags (Name, Description)
VALUES ('Python', 'Python'),
    ('JavaScript', 'JavaScript'),
    ('Java', 'Java'),
    ('C++', 'C++'),
    ('C#', 'C#'),
    ('PHP', 'PHP'),
    ('Go', 'Go'),
    ('Ruby', 'Ruby'),
    ('Swift', 'Swift'),
    ('Kotlin', 'Kotlin'),
    ('TypeScript', 'TypeScript'),
    ('Rust', 'Rust'),
    ('Dart', 'Dart'),
    ('SQL', 'SQL'),
    ('HTML', 'HTML'),
    ('CSS', 'CSS'),
    ('React', 'React'),
    ('Angular', 'Angular'),
    ('Vue', 'Vue'),
    ('Node.js', 'Node.js'),
    ('Express', 'Express'),
    ('Django', 'Django'),
    ('Flask', 'Flask'),
    ('Spring', 'Spring'),
    ('Laravel', 'Laravel'),
    ('ASP.NET', 'ASP.NET'),
    ('Ruby on Rails', 'Ruby on Rails'),
    ('Android', 'Android'),
    ('iOS', 'iOS'),
    ('Flutter', 'Flutter'),
    ('React Native', 'React Native'),
    ('Xamarin', 'Xamarin'),
    ('Electron', 'Electron'),
    ('Unity', 'Unity'),
    ('Unreal Engine', 'Unreal Engine'),
    ('MongoDB', 'MongoDB'),
    ('MySQL', 'MySQL'),
    ('PostgreSQL', 'PostgreSQL'),
    ('SQLite', 'SQLite'),
    ('Redis', 'Redis'),
    ('Firebase', 'Firebase'),
    ('Docker', 'Docker'),
    ('Kubernetes', 'Kubernetes'),
    ('AWS', 'AWS'),
    ('Azure', 'Azure'),
    ('Google Cloud', 'Google Cloud'),
    ('Linux', 'Linux'),
    ('Windows', 'Windows'),
    ('MacOS', 'MacOS'),
    ('Git', 'Git'),
    ('GitHub', 'GitHub'),
    ('GitLab', 'GitLab'),
    ('Bitbucket', 'Bitbucket'),
    ('Jira', 'Jira'),
    ('Trello', 'Trello'),
    ('Slack', 'Slack'),
    ('Discord', 'Discord'),
    ('Zoom', 'Zoom'),
    ('Google Meet', 'Google Meet'),
    ('Microsoft Teams', 'Microsoft Teams'),
    ('Facebook', 'Facebook'),
    ('Instagram', 'Instagram'),
    ('Twitter', 'Twitter'),
    ('LinkedIn', 'LinkedIn'),
    ('Snapchat', 'Snapchat'),
    ('TikTok', 'TikTok'),
    ('YouTube', 'YouTube'),
    ('Pinterest', 'Pinterest'),
    ('Reddit', 'Reddit'),
    ('Tumblr', 'Tumblr'),
    ('Quora', 'Quora'),
    ('Medium', 'Medium'),
    ('WordPress', 'WordPress'),
    ('Wix', 'Wix'),
    ('Squarespace', 'Squarespace'),
    ('Shopify', 'Shopify'),
    ('Etsy', 'Etsy'),
    ('eBay', 'eBay'),
    ('Amazon', 'Amazon'),
    ('Netflix', 'Netflix'),
    ('Spotify', 'Spotify'),
    ('Apple Music', 'Apple Music'),
    ('Google Play Music', 'Google Play Music'),
    ('SoundCloud', 'SoundCloud'),
    ('Twitch', 'Twitch'),
    ('PlayStation', 'PlayStation'),
    ('Xbox', 'Xbox'),
    ('Nintendo', 'Nintendo'),
    ('PC', 'PC'),
    ('iPhone', 'iPhone'),
    ('iPad', 'iPad'),
    ('MacBook', 'MacBook'),
    ('iMac', 'iMac'),
    ('Apple Watch', 'Apple Watch'),
    ('AirPods', 'AirPods'),
    ('Samsung', 'Samsung'),
    ('Huawei', 'Huawei'),
    ('Sony', 'Sony'),
    ('LG', 'LG'),
    ('Bose', 'Bose'),
    ('Beats', 'Beats'),
    ('Canon', 'Canon'),
    ('Nikon', 'Nikon'),
    ('Panasonic', 'Panasonic'),
    ('Fujifilm', 'Fujifilm'),
    ('Olympus', 'Olympus'),
    ('Pentax', 'Pentax'),
    ('Leica', 'Leica'),
    ('Sigma', 'Sigma'),
    ('Tamron', 'Tamron'),
    ('Tokina', 'Tokina'),
    ('Rokinon', 'Rokinon'),
    ('Zeiss', 'Zeiss'),
    ('Adobe', 'Adobe'),
    ('Microsoft', 'Microsoft'),
    ('Google', 'Google') ON CONFLICT (Name) DO NOTHING;